spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/like_tomato
    username: admin
    password: tomato25
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  mail:
    host: smtp.gmail.com
    port: 587
    username: sy01lim@naver.com
    password: Cherishable0522!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

jwt:
  secret: MyS3cr3tK3y!@#12345
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:dummy-access-key}
      secret-key: ${AWS_SECRET_KEY:dummy-secret-key}
    region: ${AWS_REGION:ap-northeast-2}  # 서울 리전
    s3:
      bucket: ${AWS_S3_BUCKET:dummy-bucket-name}
      download:
        expTime: 3600  # 1시간 (초 단위)
    upload:
      expTime: 3600    # 1시간 (초 단위)

client:
  url: ${CLIENT_URL:http://localhost:3000}