package com.like_lion.tomato.global.id;

import lombok.Getter;

@Getter
public enum DomainType {
    MEMBER("MEMBER"),
    GENERATION("GENERATION"),
    APPLICATION("APPLICATION"),
    RECRUITMENT_EMAIL_SUBSCRIPTION("RECRUIT_EMAIL_SUB"),
    RECRUITMENT_SCHEDULE("RECRUIT_SCHEDULE"),
    RECRUITMENT_COMMON_QUESTION("RECRUIT_COMMON_QUE"),
    RECRUITMENT_PART_ANSWER("RECRUIT_PART_ANS"),
    RECRUITMENT_COMMON_ANSWER("RECRUIT_COMMON_ANS"),
    RECRUITMENT_PART_QUESTION("RECRUIT_PART_QUE"),
    PROJECT("PROJECT"),
    PROJECT_IMAGE("PROJECT_IMG"),
    GALLERY("GALLERY"),
    GALLERY_IMAGE("GALLERY_IMG"),
    SESSION("SESSION"),
    SESSION_FILE("SESSION_FILE"),
    SESSION_QUIZ("SESSION_QUIZ"),
    QUIZ_QUESTION("QUIZ_QUESTION"),
    QUIZ_OPTION("QUIZ_OPT"),
    QUIZ_ANSWER("QUIZ_ANS"),
    ASSIGNMENT("ASSIGNMENT"),
    ASSIGNMENT_SUBMISSION("ASSIGNMENT_SUBMISSION"),
    REFRESH_TOKEN("REFRESH_TOKEN"),;

    private final String prefix;

    DomainType(String prefix) {
        this.prefix = prefix;
    }
}
